spring:
  application:
    # 服务名
    name: supermarket-admin
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: nacos.me:8848
    sentinel:
      transport:
        dashboard: sentinel:8090
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
dubbo:
  scan:
    base-packages: com.csqf.business.admin.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://nacos.me:8848
  provider:
    loadbalance: roundrobin
server:
  port: 0
swagger-cs:
  enabled: true
  title: supermarket
  api-base-package: com.csqf.business.admin.controller
  description: 超市导购系统 --null异常组
  version: 1.0